### ISSUE TITLE
Random App Crash (thread 'main' panicked)

### ISSUE THREAD

**Issue by arshubham** [arshubham/srtnr#19]
```
com.github.arshubham.srtnr 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:335:20
note: Run with `RUST_BACKTRACE=1` for a backtrace.
Uncaught panic, exiting
Aborted (core dumped)
```
Only happens sometimes. Running srtnr once with ```RUST_BACKTRACE=1 com.github.arshubham.srtnr``` resolves the issue for subsequent executions

**Comment by arshubham** [comment]
Backtrace:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error(Boxed { inner: ForeignOwned(0x55ea874b1120) })', src/libcore/result.rs:906:4
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::_print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::begin_panic
   6: std::panicking::begin_panic_fmt
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: core::result::unwrap_failed
             at src/libcore/macros.rs:41
  10: <core::result::Result<T, E>>::unwrap
             at src/libcore/result.rs:772
  11: srtnr::buildui::notification
             at src/buildui/mod.rs:299
  12: srtnr::buildui::ui::{{closure}}
             at src/buildui/mod.rs:191
  13: core::ops::function::impls::<impl core::ops::function::Fn<A> for &'a F>::call
             at src/libcore/ops/function.rs:232
  14: gtk::auto::button::clicked_trampoline
             at /home/shubhamarora/.cargo/registry/src/github.com-1ecc6299db9ec823/gtk-0.3.0/src/auto/button.rs:427
  15: <unknown>
  16: g_signal_emit_valist
  17: g_signal_emit
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: g_main_context_dispatch
  22: <unknown>
  23: g_main_context_iteration
  24: g_application_run
  25: <O as gio::application::ApplicationExtManual>::run
             at /home/shubhamarora/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.3.0/src/application.rs:23
  26: srtnr::main
             at src/main.rs:22
  27: __rust_maybe_catch_panic
  28: std::rt::lang_start
  29: main
  30: __libc_start_main
  31: _start
Uncaught panic, exiting
Aborted (core dumped)
```

**Comment by arshubham** [comment]
Trace on Ubuntu 18.04 daily:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at libstd/sys_common/backtrace.rs:59
             at libstd/panicking.rs:206
   3: std::panicking::default_hook
             at libstd/panicking.rs:222
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:400
   5: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:347
   6: rust_begin_unwind
             at libstd/panicking.rs:323
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:71
   8: core::panicking::panic
             at libcore/panicking.rs:51
   9: srtnr::buildui::ui
  10: gio::auto::application::startup_trampoline
  11: g_closure_invoke
  12: <unknown>
  13: g_signal_emit_valist
  14: g_signal_emit
  15: g_application_register
  16: <unknown>
  17: g_application_run
  18: srtnr::main
  19: std::rt::lang_start::{{closure}}
  20: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:305
  21: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:102
  22: std::rt::lang_start_internal
             at libstd/panicking.rs:284
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  23: main
  24: __libc_start_main
  25: _start
Uncaught panic, exiting
Aborted (core dumped)
```
